### ISSUE TITLE
Contact: W3C 2 errors (BE)

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Glass-Block-Construction#108]
![image](https://cloud.githubusercontent.com/assets/17717843/14550041/e39cb862-02f7-11e6-8177-fe0443cb5d5f.png)

**Comment by ronadtitan** [comment]
error: </script>↩<link rel='https://api.w.org/' href='http://glassblockconstruction-imp.stage.titanweb.com.au/wp-json/' />↩<link
plug in issue
